export const routeRegistry = {
  public: {
    login: '/login',
    authCallback: '/auth/callback',
  },
  protected: {
    dashboard: '/dashboard',
    repository: '/repository',
    adminConsole: '/admin',
    additionalApproverHistory: '/approver-history',
    contractDetail: '/contracts/:contractId',
  },
  api: {
    auth: {
      login: '/api/auth/login',
      logout: '/api/auth/logout',
      session: '/api/auth/session',
      refresh: '/api/auth/refresh',
    },
    contracts: {
      list: '/api/contracts',
      contractTypes: '/api/contracts/contract-types',
      departments: '/api/contracts/departments',
      pendingApprovals: '/api/contracts/pending-approvals',
      dashboard: '/api/contracts/dashboard',
      additionalApproverHistory: '/api/contracts/additional-approver-history',
      repository: '/api/contracts/repository',
      upload: '/api/contracts/upload',
      detail: '/api/contracts/:contractId',
      download: '/api/contracts/:contractId/download',
      preview: '/api/contracts/:contractId/preview',
      timeline: '/api/contracts/:contractId/timeline',
      activity: '/api/contracts/:contractId/activity',
      activityReadState: '/api/contracts/:contractId/activity/read-state',
      action: '/api/contracts/:contractId/action',
      note: '/api/contracts/:contractId/note',
      approvers: '/api/contracts/:contractId/approvers',
      assignments: '/api/contracts/:contractId/assignments',
    },
    admin: {
      users: '/api/admin/users',
      roles: '/api/admin/roles',
      userRoles: '/api/admin/users/:userId/roles',
      userStatus: '/api/admin/users/:userId/status',
      userDepartment: '/api/admin/users/:userId/department',
      teams: '/api/admin/teams',
      teamDetail: '/api/admin/teams/:teamId',
      teamPrimaryRole: '/api/admin/teams/:teamId/primary-role',
      teamLegalMatrix: '/api/admin/teams/:teamId/legal-matrix',
    },
  },
} as const
