-- Extend audit logs for contract timeline details and deterministic ordering

ALTER TABLE audit_logs
  ADD COLUMN IF NOT EXISTS target_email TEXT,
  ADD COLUMN IF NOT EXISTS note_text TEXT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'audit_logs'
      AND column_name = 'event_sequence'
  ) THEN
    ALTER TABLE audit_logs
      ADD COLUMN event_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_audit_logs_timeline_order
  ON audit_logs(tenant_id, resource_type, resource_id, event_sequence);
